frases_ataque = [
    "O inimigo avança!",
    "Cuidado!",
    "Ele vai atacar!",
    "Prepare-se!",
    "Algo está vindo!",
    "Movimento rápido!",
    "Ataque iminente!",
    "Ele partiu pra cima!",
    "Ele ergue sua arma!",
    "Um ataque está vindo!",
    "Fique atento!",
    "Ele está mirando!",
    "Você sente o perigo!",
    "Ele se aproxima!",
    "O clima fica tenso...",
    "Ele avança sem hesitar!",
    "Prepare sua defesa!",
    "Ele dispara!",
    "Um golpe está a caminho!",
    "Ele não vai recuar!",
    "Você está na mira!",
    "Ele investe com força!",
    "O inimigo acelera!",
    "Um ataque relâmpago!",
    "Ele salta para atacar!",
    "Movimento inesperado!",
    "Ele canaliza energia!",
    "Algo perigoso se aproxima!",
    "Ele prepara um golpe!",
    "Segure firme!"
]

frases_aproximacao = [
    "Você sente uma presença estranha...",
    "O chão começa a tremer...",
    "Um som ecoa pela área...",
    "O vento sopra de forma ameaçadora...",
    "Há algo observando você...",
    "Passos pesados se aproximam...",
    "Um arrepio percorre sua espinha...",
    "O silêncio fica inquietante...",
    "Algo se move nas sombras...",
    "Você ouve um rugido distante...",
    "A atmosfera fica mais pesada...",
    "Um vulto aparece ao longe...",
    "Algo está vindo na sua direção...",
    "Você sente que não está sozinho...",
    "Uma energia hostil surge por perto...",
    "O ambiente fica estranho de repente...",
    "O ar parece mais frio...",
    "Você escuta galhos se quebrando...",
    "Uma sombra cruza seu caminho...",
    "Algo observa cada movimento seu...",
    "Um barulho repentino quebra o silêncio...",
    "O clima muda drasticamente...",
    "Você sente um olhar fixo em você...",
    "Um som ameaçador ecoa ao redor...",
    "A terra vibra sob seus pés..."
]

frases_surgimento = [
    "apareceu no seu caminho!",
    "bloqueou sua passagem!",
    "saltou das sombras!",
    "emergiu do nada!",
    "se revelou diante de você!",
    "invadiu o campo de batalha!",
    "desceu pronto para lutar!",
    "se colocou à sua frente!",
    "rugiu desafiadoramente!",
    "avançou com fúria!",
    "encarou você com olhar ameaçador!",
    "surgiu com uma aura intensa!",
    "se aproximou pronto para o combate!",
    "desafiou você para uma batalha!",
    "entrou na arena com tudo!",
    "apareceu envolto em energia!",
    "saltou na sua frente!",
    "ergueu-se pronto para atacar!",
    "mostrou que não veio para brincar!",
    "invadiu seu território!",
    "chegou com sede de batalha!",
    "rompeu o silêncio com um grito!",
    "surgiu com olhos brilhando!",
    "desafiou sua coragem!",
    "avançou sem hesitar!"
]